# Lock on lid close
bindl = , switch:on:Lid Switch, exec, OMARCHY_LOCK_ONLY=true omarchy-system-lock

# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
# $browser = omarchy-launch-browser
$browser = firefox

unbind = SUPER SHIFT, J
unbind = SUPER SHIFT, K

bind = SUPER CONTROL, K, exec, ~/.local/share/omarchy/bin/omarchy-menu-keybindings

bind = SUPER SHIFT, S, layoutmsg, togglesplit

unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

bind = SUPER SHIFT, H, movefocus, l
bind = SUPER SHIFT, J, movefocus, d
bind = SUPER SHIFT, K, movefocus, u
bind = SUPER SHIFT, L, movefocus, r

bind = SUPER SHIFT ALT, H, swapwindow, l
bind = SUPER SHIFT ALT, J, swapwindow, d
bind = SUPER SHIFT ALT, K, swapwindow, u
bind = SUPER SHIFT ALT, L, swapwindow, r

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private-window
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, T, Toggle window floating/tiling, togglefloating,
bindd = SUPER, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER, G, Signal, exec, omarchy-launch-or-focus signal "uwsm app -- signal-desktop"
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm-app -- obsidian"
bindd = SUPER, slash, Passwords, exec, uwsm app -- 1password

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
# bindd = SUPER, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
bindd = SUPER, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
bindd = SUPER, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, W, Impala, exec, omarchy-launch-wifi

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, SPACE
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu
